### PR TITLE
Minor Changes: Typos and wrong function calling

### PR DESCRIPTION
**Pull request by AlexNair**
I updated from 0.4 to the current development branch and found a lot of changes in the architecture.
It seems that some changes did not make it to all classes and functions.

This are the minor changes i had to make to get it working for me. 
Can you please check or discuss them here

### CODE REVIEW

**Comment by ebroecker** [comment]
@AlexNair 
Thanks for your PR.

You are right, I forgot more than one point to update to the new architecture.

I only have one remark to you changes. Could you please review?

Thanks again

**Comment by AlexNair** [comment]
What kind of remark do you mean? 
Travis is happy now, if you meant that...

**Comment by AlexNair** [comment]
You are right!
Its better to use the api.
Changed it and it works

**Comment by ebroecker** [comment]
Thanks

**Pull request merged**
