### PR TITLE
Update Scapy format

### PR DESCRIPTION
**Pull request by polybassa**
I've updated the implementation of SignalFields in Scapy. This should keep canmatrix up-to-date, as well.
This PR can be merged, after https://github.com/secdev/scapy/pull/2253 is merged into mainline Scapy.

### CODE REVIEW

**Comment by polybassa** [comment]
@ebroecker How could multiplexers be implemented in canmatrix -> scapy

**Comment by ebroecker** [comment]
@polybassa 

we discussed here ... 
https://github.com/polybassa/AutomotiveScapyUtils/issues/18#issuecomment-459011344

**Comment by polybassa** [comment]
Merged in Mainline

**Comment by ebroecker** [comment]
I think, this can be closed, because it's contained in #400

**Pull request closed without merging**
