### PR TITLE
Set initial_value to physical value

### PR DESCRIPTION
**Pull request by pierreluctg**
Currently the initial_value is incorrectly set to the signal raw value.

### CODE REVIEW

**Comment by ebroecker** [comment]
Hi @pierreluctg,

why is raw value as initial_value wrong in your eyes?
So you think initial_value should be physical value.
I thought it should be the raw value, because with this we don't have problems regarding scaling.

**Comment by pierreluctg** [comment]
Hi @ebroecker, based on the comment/type hint here https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/canmatrix.py#L173, `initial_value` is a `canmatrix.types.PhysicalValue`

It's also a physical value according to the logic in `phys2raw` here https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/canmatrix.py#L407 else the `intitial_value` would be returned directly without scaling.

We can change the type hinting and logic to have `initial_value` as a `canmatrix.types.RawValue` if that is your preference.

**Comment by ebroecker** [comment]
@pierreluctg 
I feared already that it's inconsistent. 
I don't want to prescribe something. 
Just want to discuss.
My only argument is scaling.  But as far as I remembre, there are formats which use physical values and formats wich use raw value.

So anyway, what du You think ist the more intuitive way to to it?

**Comment by pierreluctg** [comment]
IMO, the `initial_value` attribute should be a physical value, just like `min`, `max`, etc.
From a canmatrix API point of view it also make sense to have all the attributes as physical values.

This is in line with how application like Vector CANdb++ is displaying the information.

This also make the distinction between the DCB attribute `GenSigStartValue` (raw initial value) and `initial_value` (physical initial value).

**Comment by ebroecker** [comment]
Hi @pierreluctg 
thanks for clarification!

**Pull request merged**
