### PR TITLE
Create Signal.enum2raw() instead of using basestring in Signal.phys2raw()

### PR DESCRIPTION
**Pull request by altendky**
Issue #133 

@pierreluctg, I don't seem to be able to add you as a reviewer but please do weigh in on this if you want.

### CODE REVIEW

**Comment by pierreluctg** [comment]
With this change, `raw2phys` (with `decodeToStr=True`) and `phys2raw` are no longer symmetrical. Do we want to keep them symmetrical?

Also, do we want to rename `decodeToStr` param to something else like `decodeEnum`?

**Comment by altendky** [comment]
Good point.  I'd probably just make a `raw2enum()`.  Then there is no need for a parameter and the return type for each function is consistent.  I'll go update the PR in a couple minutes.

Enums should probably be real Python enumerations...  but that's a bit bigger thing to consider.  Even just having them centralized on a database rather than stored in each signal would be good.  I did some sort of hack on for that, maybe just for .sym, but I don't recall the details off the top of my head.  It was important because outputting to a .sym you need the enumeration definition once at the top of the file and then each signal only refers to the name from the definition.

**Comment by pierreluctg** [comment]
@altendky, `Frame` encode and decode also need to be updated while keeping the ability to encode using values from enums and decode enums for signals with enums.

**Comment by altendky** [comment]
@pierreluctg @ebroecker I think part of the issue here is that we are using strings at all.  Maybe I can make an interrim change to address the `Frame.encode()` and `decode()` methods but what do you think of having `enum.IntEnum`'s for enumerations rather than strings and integers?  This would force the conversion to/from an integer/enumerator to be done by the application code.  I guess that would mean that the interrim here would be to simply not support strings at all (remove the new `enum2raw()` and `raw2enum()` functions).

Here's a quick example of `enum.IntEnum`.

py2: https://repl.it/@altendky/basic-IntEnum-py2
py3: https://repl.it/@altendky/basic-IntEnum-py3

**Comment by ebroecker** [comment]
@altendky 
is there anything todo or can I merge (after solving conflicts?)

**Comment by altendky** [comment]
What thoughts do you have on my last comment?  We really need to get away from accepting two different types in a single parameter. It makes things much more confusing when you try to mix functionality.

**Comment by ebroecker** [comment]
yes, you are surely right. But is this not exactly what this commit does ? 
There may be more places in the code where curently more types are allowed, but this one would be finished after this pr? 
Do I miss something?

**Comment by altendky** [comment]
As I recall, this is incomplete as per @pierreluctg's last comment.  But I'll have to take a look next week.

**Comment by ebroecker** [comment]
OK, thanks

**Pull request closed without merging**
