### PR TITLE
Overall code improvements

### PR DESCRIPTION
**Pull request by JulienGrv**
I made changes to tox as I found it difficult to understand otherwise

### CODE REVIEW

**Comment by anphucnguyen** [comment]
Some commits are duplicated in #554

**Comment by JulienGrv** [comment]
Yes, this branch is a continuation. I first came to do a tiny change to the code base but decided to improve other things in the end

**Comment by anphucnguyen** [comment]
I see appveyor noticed that they supported python 3.9, so i wonder why it's not working on this repo

**Review by ebroecker — APPROVED** [review]

**Comment by JulienGrv** [comment]
> I see appveyor noticed that they supported python 3.9, so i wonder why it's not working on this repo

I was wondering the same but didn't find why so I leave for now.

**Pull request merged**
