### PR TITLE
Fix some bugs in FIBEX export

### PR DESCRIPTION
**Pull request by akaanich-technica**
## Changes:
* Fixed duplicate ids when two signals have same name in different frames
* Added CONNECTORS element
* Fixed location of PROCESSING-INFORMATION
* Added the bit length of each signal

### CODE REVIEW

**Comment by akaanich-technica** [comment]
Failure to due: `The job exceeded the maximum log length, and has been terminated.`

**Comment by ebroecker** [comment]
@ akaanich-technica 

thanks for this PR.
So FIBEX code is so usable for you? 
I once implemented it only from white paper - without any chance to test...

**Comment by akaanich-technica** [comment]
@ebroecker It is usable:
We used the DBC files from https://github.com/commaai/opendbc and converted them to FIBEX, and consume in our own toolchain.

The only problem that I couldn't 100% fix is that some DBC files had duplicate signal names, duplicate frame names, and sometimes even duplicate ecu names.

The one thing I am sure of, is that it is valid in DBC to have two different signals with the same name, as long as they reside in different frames, so I fixed that in the FIBEX exporter, the rest I wasn't so sure about.

**Comment by ebroecker** [comment]
Hi @akaanich-technica ,

thanks for pointing to opendbc - didn't know this...

Most tools won't allow signals with equal names. You could even use canmatrix to fix this:
```
python -m canmatrix.cli.convert source.dbc target.dbc
```
should create a dbc with uniq signal names (`--no-dbcUniqueSignalNames` is the option to disable this behaviour)

In second step convert to fibex as before...

**Comment by akaanich-technica** [comment]
@ ebroecker Thanks for the tip,
I see this PR is failing App Veyor, but I can't pinpoint what test cases are failing.
Is this PR failing due to my changes, or something off with App Veyor configuration?

**Comment by akaanich-technica** [comment]
@ebroecker AppVoyer is failing in the development branch as well, so those changes should be good to merge, no?

**Pull request merged**
