### PR TITLE
Fixes to master branch

### PR DESCRIPTION
**Pull request by 4cylinder**
I tried downloading the master branch and it simply did not work, largely due to typos in variable names scattered throughout the code. I've corrected those issues and also optimized the xls generator.

### CODE REVIEW

**Comment by ebroecker** [comment]
Hi,

thanks for sending a pr.
I just now saw, that master branch seems not to work out of fhe box.
This shouldn't happen.

Did you try the development-branch?

this pr makes problems with  travis also. 
Could you have a further look on it?

**Comment by 4cylinder** [comment]
Yeah I tried the development branch and it also contained many typos - more than the master branch did.

**Comment by ebroecker** [comment]
could you try development branch once more? I did some improvements, so maybe your usecase works now?

**Comment by 4cylinder** [comment]
Hi, sorry for the long delay - I got reassigned and didn't get back to this project for a while.

Everything is fine though I prefer to have the XLS have normally positioned headers (easy self-fix though :))

**Pull request closed without merging**
