### PR TITLE
move convert and compare to submodule "cli"

### PR DESCRIPTION
**Pull request by ebroecker**
now split em in functionality and library

### CODE REVIEW

**Comment by ebroecker** [comment]
@Funth0mas 
is that more the idea of splitting?

**Comment by Funth0mas** [comment]
Yes this is how I would do it too.

**Comment by ebroecker** [comment]
@Funth0mas 
seems ok for merge now, what do you think?

**Comment by Funth0mas** [comment]
I think the code is OK but the old tests seems to need small fix (in fact revert to previous version) to satisfy travis, otherwise we get build failure in development branch I think.

**Pull request merged**
